# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('password', models.CharField(max_length=30)),
                ('password_confirmation', models.CharField(max_length=30)),
            ],
        ),
    ]
