# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-27 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20160624_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Time',
            field=models.DateTimeField(),
        ),
    ]
